name: Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://www.opencode.net/himdek/Simple-Kickoff-for-Plasma"
      env:
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "opencode.net"
        GITLAB_USERNAME: "himdek"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }} // Generate here: https://www.opencode.net/-/profile/personal_access_tokens
        GITLAB_PROJECT_ID: "2671" // https://gitlab.com/<namespace>/<repository>/edit
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} // https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
